version: '3.4'

services:
  datafi-core-api:
    environment:
      NODE_ENV: local
      SWAGGER_PATH: /datafi-core-api
      PORT: 8080
      
  database-mongo:
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
      MONGO_INITDB_DATABASE: datafi
    volumes:
      - ./src/database/mongo-entrypoint:/docker-entrypoint-initdb.d
      - mongodb:/data/db
      - mongoconfig:/data/configdb

    ports:
      - 27017:27017

