version: '3.4'

name: 'datafi'

services:
  database-mongo:
      image: mongo:4.2.23
      container_name: datafi-database-mongo
      profiles:
        - database

  datafi-core-api:
    image: datafi-core-api-${TAG:-latest}
    container_name: datafi-core-api
    build:
      context: .
      dockerfile: src/datafi-core-api/Dockerfile
    profiles:
      - services
  
networks:
  default:
    name: 'datafi-network'
    driver: bridge

volumes:
  mongodb:
    driver: local
  mongoconfig:
    driver: local