version: '3.4'

name: 'datafi'

services:

  database:
    image: database:${TAG:-latest}
    container_name: database
    build:
      context: infrastructure/database
      dockerfile: ./Dockerfile
    profiles:
      - infrastructure
      - database


  
networks:
  default:
    name: 'datafi-network'
    driver: bridge

