require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/field_templates", type: :request do
  
  # This should return the minimal set of attributes required to create a valid
  # FieldTemplate. As you add validations to FieldTemplate, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      FieldTemplate.create! valid_attributes
      get field_templates_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      field_template = FieldTemplate.create! valid_attributes
      get field_template_url(field_template)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_field_template_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "renders a successful response" do
      field_template = FieldTemplate.create! valid_attributes
      get edit_field_template_url(field_template)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new FieldTemplate" do
        expect {
          post field_templates_url, params: { field_template: valid_attributes }
        }.to change(FieldTemplate, :count).by(1)
      end

      it "redirects to the created field_template" do
        post field_templates_url, params: { field_template: valid_attributes }
        expect(response).to redirect_to(field_template_url(FieldTemplate.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new FieldTemplate" do
        expect {
          post field_templates_url, params: { field_template: invalid_attributes }
        }.to change(FieldTemplate, :count).by(0)
      end

    
      it "renders a response with 422 status (i.e. to display the 'new' template)" do
        post field_templates_url, params: { field_template: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested field_template" do
        field_template = FieldTemplate.create! valid_attributes
        patch field_template_url(field_template), params: { field_template: new_attributes }
        field_template.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the field_template" do
        field_template = FieldTemplate.create! valid_attributes
        patch field_template_url(field_template), params: { field_template: new_attributes }
        field_template.reload
        expect(response).to redirect_to(field_template_url(field_template))
      end
    end

    context "with invalid parameters" do
    
      it "renders a response with 422 status (i.e. to display the 'edit' template)" do
        field_template = FieldTemplate.create! valid_attributes
        patch field_template_url(field_template), params: { field_template: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested field_template" do
      field_template = FieldTemplate.create! valid_attributes
      expect {
        delete field_template_url(field_template)
      }.to change(FieldTemplate, :count).by(-1)
    end

    it "redirects to the field_templates list" do
      field_template = FieldTemplate.create! valid_attributes
      delete field_template_url(field_template)
      expect(response).to redirect_to(field_templates_url)
    end
  end
end
