require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/plan_teams", type: :request do
  
  # This should return the minimal set of attributes required to create a valid
  # PlanTeam. As you add validations to PlanTeam, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      PlanTeam.create! valid_attributes
      get plan_teams_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      plan_team = PlanTeam.create! valid_attributes
      get plan_team_url(plan_team)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_plan_team_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "renders a successful response" do
      plan_team = PlanTeam.create! valid_attributes
      get edit_plan_team_url(plan_team)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new PlanTeam" do
        expect {
          post plan_teams_url, params: { plan_team: valid_attributes }
        }.to change(PlanTeam, :count).by(1)
      end

      it "redirects to the created plan_team" do
        post plan_teams_url, params: { plan_team: valid_attributes }
        expect(response).to redirect_to(plan_team_url(PlanTeam.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new PlanTeam" do
        expect {
          post plan_teams_url, params: { plan_team: invalid_attributes }
        }.to change(PlanTeam, :count).by(0)
      end

    
      it "renders a response with 422 status (i.e. to display the 'new' template)" do
        post plan_teams_url, params: { plan_team: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested plan_team" do
        plan_team = PlanTeam.create! valid_attributes
        patch plan_team_url(plan_team), params: { plan_team: new_attributes }
        plan_team.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the plan_team" do
        plan_team = PlanTeam.create! valid_attributes
        patch plan_team_url(plan_team), params: { plan_team: new_attributes }
        plan_team.reload
        expect(response).to redirect_to(plan_team_url(plan_team))
      end
    end

    context "with invalid parameters" do
    
      it "renders a response with 422 status (i.e. to display the 'edit' template)" do
        plan_team = PlanTeam.create! valid_attributes
        patch plan_team_url(plan_team), params: { plan_team: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested plan_team" do
      plan_team = PlanTeam.create! valid_attributes
      expect {
        delete plan_team_url(plan_team)
      }.to change(PlanTeam, :count).by(-1)
    end

    it "redirects to the plan_teams list" do
      plan_team = PlanTeam.create! valid_attributes
      delete plan_team_url(plan_team)
      expect(response).to redirect_to(plan_teams_url)
    end
  end
end
